# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-14 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='scales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_name', models.CharField(max_length=100)),
                ('scale_details', models.TextField(max_length=100)),
                ('scale_document_url', models.URLField(max_length=100)),
                ('scale_image', models.ImageField(upload_to='images', verbose_name='Image')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['scale_name'],
            },
        ),
    ]
