# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-14 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scales',
            name='scale_details',
            field=models.TextField(max_length=3000),
        ),
    ]
