# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-14 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161014_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='scales',
            name='category',
            field=models.ManyToManyField(to='app.Category'),
        ),
    ]
